name: '🚔'
on: [ push, pull_request ]
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Claim the land'
        run: 'curl --header Accept:text/plain https://ipv4.games/claim?name=nothub@github 2> /dev/null || true'
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: make check
      - run: make release
        if: startsWith(github.event.ref, 'refs/tags/v')
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          body: 'Release generated at commit: ${{ github.sha }}'
          files: 'out/*'
